const { makeTermGrid, darkCyan, mediumCyan, cyan } = require('./lib/index.js')

const tg = makeTermGrid(10, 30)
tg.clear()
tg.set(1, 1, '%', darkCyan, cyan)
tg.text(2, 2, 'hello', 2, 3)
tg.draw()
tg.set(1, 2, '%', cyan, darkCyan)
tg.text(3, 2, 'world', mediumCyan, 3)
tg.draw()
tg.reset()
